version: '3'
volumes:
  mysql_data:
  mysql_conf:
  mysql_log:
  redis_data:
  nginx_conf:
  nginx_html:
  nginx_logs:
  rabbitmq_data:
  elasticsearch_plugins:
  elasticsearch_data:
  logstash_conf:
  mongo_db:
  minio_data:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql #数据文件目录挂载
      - mysql_conf:/etc/mysql #配置文件目录挂载
      - mysql_log:/var/log/mysql #日志文件目录挂载
  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data #数据文件目录挂载
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - nginx_conf:/etc/nginx #配置文件目录挂载
      - nginx_html:/usr/share/nginx/html #静态资源根目录挂载
      - nginx_logs:/var/log/nginx #日志文件目录挂载
    ports:
      - 80:80
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq #数据文件目录挂载
    environment:
      RABBITMQ_DEFAULT_USER: mall
      RABBITMQ_DEFAULT_PASS: mall
      RABBITMQ_DEFAULT_VHOST: /mall
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置es使用的jvm内存大小
      - "xpack.security.enabled=false" #禁用安全认证（开发环境）
    volumes:
      - elasticsearch_plugins:/usr/share/elasticsearch/plugins #插件文件目录挂载
      - elasticsearch_data:/usr/share/elasticsearch/data #数据文件目录挂载
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:8.10.2
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
      - "xpack.monitoring.enabled=false"
    depends_on:
      - elasticsearch #logstash在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:8.10.2
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  mongo:
    image: mongo:7.0
    container_name: mongo
    volumes:
      - mongo_db:/data/db #数据文件目录挂载
    ports:
      - 27017:27017
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001" #指定数据目录及console运行端口启动
    volumes:
      - minio_data:/data #数据目录挂载
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - 9090:9000
      - 9001:9001
