server:
  port: 8085

spring:
  application:
    name: mall-search-pg

  datasource:
    url: jdbc:postgresql://localhost:5433/mall_search
    username: mall
    password: mall
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha